### ISSUE TITLE
The gauge is not shown as half gauge as expected

### ISSUE THREAD

**Issue by helto4real** [helto4real/lovelace-custom-cards#2]
The gauge is not showing half the gauge as expected using canvas gauge example.

**Comment by helto4real** [comment]
This is currently by design. The canvas lib is not setting default values as it should when running under shadow root. As a workaround set all border settings to remove border:

```yaml
        borderShadowWidth: 0
        borderOuterWidth: 0
        borderMiddleWidth: 0
        borderInnerWidth: 0
        borders: false
```

This workaround should work until i figured out how to trigger defaults in the canvas lib.
